kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ./patch-operator-scheduling.yaml
- ./sriovoperatorconfig.yaml
- ./sriovnetworknodepolicy.yaml
#- ./sriovnetwork.yaml
# SriovNetwork is commented out as it is needed only in specific scenarios and in the experiment namespace.